# Generated by Django 2.1.4 on 2019-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32, unique=True)),
                ('p_users', models.ManyToManyField(to='Admin.AdminUser')),
            ],
        ),
    ]
