# Generated by Django 2.1.4 on 2019-04-23 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=64)),
                ('l_img', models.CharField(max_length=256)),
                ('l_age', models.IntegerField(default=0)),
                ('l_height', models.IntegerField(default=160)),
                ('l_feature', models.CharField(max_length=256)),
                ('l_f_feature', models.CharField(max_length=256)),
                ('l_isdna', models.BooleanField(default=False)),
                ('l_f_date', models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 56, 6, 627789))),
                ('l_f_site', models.CharField(max_length=256)),
                ('l_r_tel', models.IntegerField(max_length=16)),
                ('l_r_unit', models.CharField(max_length=256)),
                ('l_p_date', models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 56, 6, 628809))),
                ('l_r_info', models.CharField(max_length=256)),
            ],
        ),
    ]
