# Generated by Django 2.1.4 on 2019-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_auto_20190424_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loster',
            name='l_f_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loster',
            name='l_p_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
