# Generated by Django 2.1.4 on 2019-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_auto_20190425_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loster',
            name='l_r_tel',
            field=models.CharField(max_length=16),
        ),
    ]
