# Generated by Django 2.1.4 on 2019-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_auto_20190425_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loster',
            name='l_r_tel',
            field=models.CharField(max_length=32),
        ),
    ]
