# Generated by Django 2.1.4 on 2019-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_username', models.CharField(max_length=32, unique=True)),
                ('r_password', models.CharField(max_length=256)),
                ('r_tel', models.CharField(max_length=32)),
                ('r_site', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(default=False)),
                ('r_permission', models.IntegerField(default=0)),
            ],
        ),
    ]
